services:
  api:
    build:
      context: .
      dockerfile: PRN232.LMS.API/Dockerfile
    image: prn232-lms-api:1.0.0
    container_name: lms-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=lms_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Issuer=PRN232.LMS
      - Jwt__Audience=PRN232.LMS.Client
      - Jwt__Secret=PRN232-LMS-Docker-Jwt-Secret-For-Lab-Only-Change-Me-2026
      - Jwt__AccessTokenMinutes=30
      - Jwt__RefreshTokenDays=7
    depends_on:
      - postgres
      - redis
    networks:
      - lms_network

  postgres:
    image: postgres:16-alpine
    container_name: lms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms_network

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lms_network

  dozzle:
    image: amir20/dozzle:latest
    container_name: lms-dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lms_network

networks:
  lms_network:
    driver: bridge

volumes:
  postgres_data:
