using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using PRN232.LMS.Repositories.Data;
using PRN232.LMS.Repositories.Entities;
using PRN232.LMS.Repositories.Extensions;
using PRN232.LMS.Services.Services;

namespace PRN232.LMS.Services.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddLmsApplication(
        this IServiceCollection services,
        string connectionString)
    {
        services.AddLmsRepositories(connectionString);

        services.AddScoped<ISemesterService, SemesterService>();
        services.AddScoped<ISubjectService, SubjectService>();
        services.AddScoped<ICourseService, CourseService>();
        services.AddScoped<IStudentService, StudentService>();
        services.AddScoped<IEnrollmentService, EnrollmentService>();
        services.AddScoped<IAuthService, AuthService>();
        services.AddScoped<IPasswordHasher<User>, PasswordHasher<User>>();
        services.AddScoped<IPasswordHasherService, PasswordHasherService>();
        services.AddScoped<IJwtTokenService, JwtTokenService>();

        return services;
    }

    public static void InitializeLmsDatabase(this IServiceProvider serviceProvider)
    {
        using var scope = serviceProvider.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<LmsDbContext>();
        var passwordHasherService = scope.ServiceProvider.GetRequiredService<IPasswordHasherService>();

        dbContext.Database.EnsureCreated();
        EnsureAuthSchema(dbContext);
        SeedDemoUsers(dbContext, passwordHasherService);
    }

    private static void EnsureAuthSchema(LmsDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "Users" (
                "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
                "Username" character varying(50) NOT NULL,
                "PasswordHash" character varying(255) NOT NULL,
                "Role" character varying(20) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
            );
            """);

        dbContext.Database.ExecuteSqlRaw("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username"
            ON "Users" ("Username");
            """);

        dbContext.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "RefreshTokens" (
                "RefreshTokenId" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" integer NOT NULL,
                "TokenHash" character varying(255) NOT NULL,
                "ExpiresAt" timestamp with time zone NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "RevokedAt" timestamp with time zone NULL,
                CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("RefreshTokenId"),
                CONSTRAINT "FK_RefreshTokens_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId")
                    ON DELETE CASCADE
            );
            """);

        dbContext.Database.ExecuteSqlRaw("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash"
            ON "RefreshTokens" ("TokenHash");
            """);

        dbContext.Database.ExecuteSqlRaw("""
            CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId"
            ON "RefreshTokens" ("UserId");
            """);
    }

    private static void SeedDemoUsers(LmsDbContext dbContext, IPasswordHasherService passwordHasherService)
    {
        SeedDemoUser(dbContext, passwordHasherService, "admin", "Admin");
        SeedDemoUser(dbContext, passwordHasherService, "user", "User");

        dbContext.SaveChanges();
    }

    private static void SeedDemoUser(
        LmsDbContext dbContext,
        IPasswordHasherService passwordHasherService,
        string username,
        string role)
    {
        if (dbContext.Users.Any(user => user.Username == username))
        {
            return;
        }

        var user = new User
        {
            Username = username,
            Role = role,
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };

        user.PasswordHash = passwordHasherService.HashPassword(user, "123456");
        dbContext.Users.Add(user);
    }
}
